onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - contentlayer2
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  micromatch@<4.0.8: '>=4.0.8'
  next@>=0.9.9 <14.2.31: '>=14.2.31'
  next@>=0.9.9 <14.2.32: '>=14.2.32'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  next@>=13.3.0 <14.2.34: '>=14.2.34'
  next@>=13.3.1-canary.0 <14.2.35: '>=14.2.35'
  qs@<6.14.1: '>=6.14.1'
